# Generated by Django 4.2.3 on 2024-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On way', 'On way'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=40),
        ),
    ]
